---
- name: "Move backend files to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Install package dependencies"
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz -C backend
    rm artifact.tar.gz
    cd backend/
    npm install
    pm2 stop default
    pm2 start npm -- start