---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: artifact.tar.gz
    dest: "~/backend_app/artifact.tar.gz"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend_app
    tar -xvzf artifact.tar.gz
    rm -rf artifact.tar.gz

- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    npm install

- name: "Executing node"
  shell: |
    export
    cd ~/backend_app
    pm2 start main.js
  register: execute_node

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu