---
- name: "Move backend files to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Check for tar file"
  become: true
  command:
      ls -l /home/ubuntu/artifact.tar.gz

- name: "Install package dependencies"
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz 
    rm artifact.tar.gz

- name: "Check and install npm"
  become: true
  command: npm install
    args:
      chdir: /home/ubuntu/backend

- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
    args:
      chdir: /home/ubuntu/backend/dist

