---
- name: "Move backend files to server."
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Check for tar file"
  become: true
  command:
      ls -l /home/ubuntu/artifact.tar.gz

- name: "Install package dependencies"
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz 
    
- name: "Check and install npm"
  become: true
  become_user: root
  become_method: sudo
  command: 
#     apt update
#     apt-get --assume-yes install nodejs npm
      apt install --assume-yes npm nodesjs 1> apt.out 2> apt.err
     npm i pm2 -g 
  args:
      chdir: /home/ubuntu/

- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true

- name: "start server"
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env

